name: github pages

on:
  push:
    branches:
      - master
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      - uses: proulxsamuel/deploy-blazor-to-gh-pages@master
        with:
          project_path: './BasicBlazorWebAssemblyPwaGithubPagesApp/'